@extends('admin.layout')
@section('title',$customer->name)
@section('content')
<div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><a href="{{ route('admin.users.index') }}" class="text-sm text-cyan-400">‹ Users</a><h1 class="mt-3 text-3xl font-black">{{ $customer->name }}</h1><p class="mt-2 text-slate-400">{{ $customer->telegram_username?'@'.$customer->telegram_username:'No username' }} · Telegram {{ $customer->telegram_id }}</p></div><form method="post" action="{{ route('admin.users.block',$customer) }}">@csrf @method('PATCH')<button onclick="return confirm('Change this user status?')" class="rounded-xl px-5 py-3 font-bold {{ $customer->is_blocked?'bg-emerald-400 text-slate-950':'bg-rose-500 text-white' }}">{{ $customer->is_blocked?'Unblock User':'Block User' }}</button></form></div>
<div class="grid gap-6 xl:grid-cols-[340px_1fr]">
 <div class="space-y-6"><div class="rounded-2xl border border-white/10 bg-slate-900 p-6"><p class="text-sm text-slate-400">Current wallet</p><p class="mt-2 text-4xl font-black">${{ number_format((float)$customer->balance,2) }}</p></div>
 <form method="post" action="{{ route('admin.users.balance',$customer) }}" class="rounded-2xl border border-white/10 bg-slate-900 p-6">@csrf<h2 class="mb-5 text-xl font-bold">Adjust balance</h2>@if($errors->any())<div class="mb-4 rounded-xl bg-rose-400/10 p-3 text-sm text-rose-300">{{ $errors->first() }}</div>@endif<label class="mb-4 block"><span class="mb-2 block text-sm text-slate-400">Amount</span><input name="amount" type="number" step="0.00000001" placeholder="10 or -5" required class="w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label><label class="block"><span class="mb-2 block text-sm text-slate-400">Reason</span><input name="reason" maxlength="255" required placeholder="Refund, promotion..." class="w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3"></label><button onclick="return confirm('Apply this wallet adjustment?')" class="mt-5 rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Apply adjustment</button></form></div>
 <div class="space-y-6">
  <section class="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 class="mb-4 text-xl font-bold">Wallet ledger</h2><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead class="text-slate-400"><tr><th class="pb-3">Type</th><th>Amount</th><th>Before</th><th>After</th><th>Description</th><th>Date</th></tr></thead><tbody>@forelse($transactions as $tx)<tr class="border-t border-white/10"><td class="py-3">{{ strtoupper($tx->type) }}</td><td class="{{ (float)$tx->amount>=0?'text-emerald-300':'text-rose-300' }}">{{ (float)$tx->amount>=0?'+':'' }}{{ rtrim(rtrim((string)$tx->amount,'0'),'.') }}</td><td>{{ number_format((float)$tx->balance_before,2) }}</td><td>{{ number_format((float)$tx->balance_after,2) }}</td><td>{{ $tx->description }}</td><td>{{ $tx->created_at->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="6" class="py-6 text-center text-slate-500">No transactions.</td></tr>@endforelse</tbody></table></div></section>
  <div class="grid gap-6 lg:grid-cols-2"><section class="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 class="mb-4 text-xl font-bold">Recent orders</h2>@forelse($orders as $order)<div class="flex justify-between border-t border-white/10 py-3 first:border-0"><span class="font-mono">{{ $order->public_id }}</span><span>${{ number_format((float)$order->total,2) }} · {{ strtoupper($order->status) }}</span></div>@empty<p class="text-slate-500">No orders.</p>@endforelse</section><section class="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 class="mb-4 text-xl font-bold">Recent deposits</h2>@forelse($deposits as $deposit)<div class="flex justify-between border-t border-white/10 py-3 first:border-0"><span>{{ rtrim(rtrim((string)$deposit->amount,'0'),'.') }} USDT</span><span>{{ $deposit->method?->name }} · {{ strtoupper($deposit->status) }}</span></div>@empty<p class="text-slate-500">No deposits.</p>@endforelse</section></div>
 </div>
</div>
@endsection
